const items = [
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '../../../Images/Breakfast/breakfast1.png',
		desc: 'How we dream about our future',
	},
];
